spring.application.name=localspotify
# 1. Cấu hình Server & File Upload
server.port=8080
# Cho phép upload file nhạc tối đa 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# Upload directory for audio files
upload.dir=uploads/audio
# 2. Kết nối Database MySQL
# Đảm bảo tên database local_spotify_db khớp với script SQL
# 2. Cấu hình Database (Tự động nhận diện môi trường Cloud hoặc Local)
# Cấu hình Database kết nối thẳng lên Cloud Aiven
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-1e46e059-local-spotify.l.aivencloud.com:19597/defaultdb?useSSL=true&requireSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_BA5fPVf3SSv4k22f9at}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Kích hoạt Hibernate tự động tạo bảng lên Cloud
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình Cloudinary
cloudinary.cloud-name=drrgg0zdg
cloudinary.api-key=526395131877512
cloudinary.api-secret=Ix4UecOKx8sf4_y1mpHZIQ8MMLc